[package]
name = "stomper"
version = "0.1.0"
authors = ["Toby Grasl <herblet@knowledge42.com>"]
edition = "2018"
description = "A crate provides an implementation of the STOMP 1.2 protocol."
homepage = "https://github.com/herblet/stomper"
license = "MIT"

[dependencies]
tokio = { version = "^1.5", features = ["full"] }
tokio-stream = "0.1.5"
futures = { version = "^0.3", default-features = false, features = ["alloc"] }
tokio-tungstenite = "^0.14"
stomp-parser = "^0.2.0"
async-map = "^0.2.0"
log = "^0.4"
env_logger = "^0.8"
im = "^15.0.0"
uuid = { version = "^0.8.2", features = ["v4"] }

[dependencies.tungstenite]
version = "^0.13.0"
default-features = false

[dev-dependencies]
mockall = "0.9.1"