name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Run CI
        uses: actions-rs/cargo@v1
        env:
          CARGO_MAKE_RUN_CODECOV: "true"
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          command: make
          args: ci-flow
